#!/bin/bash

#to find the IPTABLES
PATH=$PATH:/usr/sbin
echo "$(jq -r ".route_table_num" /etc/mrvpn.conf)" MRVPN >/etc/iproute2/rt_tables.d/MRVPN.conf

while ip rule del fwmark "$(jq -r ".route_table_num" /etc/mrvpn.conf)" table MRVPN >/dev/null 2>&1; do
  echo "Removing duplicate ip rules"
done
ip rule add fwmark "$(jq -r ".route_table_num" /etc/mrvpn.conf)" table MRVPN

iptables -t nat -C PREROUTING -i wg-firezone -p udp --dport 53 -j DNAT --to-destination \
  $(jq -r ".vpn_host" /etc/mrvpn.conf):1053 -m comment --comment "MRVPN_DNS_UDP" >/dev/null 2>&1 ||
  iptables -t nat -A PREROUTING -i wg-firezone -p udp --dport 53 -j DNAT --to-destination \
    $(jq -r ".vpn_host" /etc/mrvpn.conf):1053 -m comment --comment "MRVPN_DNS_UDP"

iptables -t nat -C PREROUTING -i wg-firezone -p tcp --dport 53 -j DNAT --to-destination \
  $(jq -r ".vpn_host" /etc/mrvpn.conf):1053 -m comment --comment "MRVPN_DNS_TCP" >/dev/null 2>&1 ||
  iptables -t nat -A PREROUTING -i wg-firezone -p tcp --dport 53 -j DNAT --to-destination \
    $(jq -r ".vpn_host" /etc/mrvpn.conf):1053 -m comment --comment "MRVPN_DNS_TCP"


iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu -m comment \
  --comment "MRVPN_MSS_CLAMP" >/dev/null 2>&1 ||
  iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu -m comment \
    --comment "MRVPN_MSS_CLAMP"

#wait till outernet tunnel is up
until ping 1.1.1.1 -I  mrvpn-wg-outer -c 1
do
        echo "Waiting till outernet tunnel become ready"
        sleep 0.1
done

iptables -t nat -C POSTROUTING -o mrvpn-wg-outer -j MASQUERADE >/dev/null 2>&1 ||
  iptables -t nat -A POSTROUTING -o mrvpn-wg-outer -j MASQUERADE

#move all outgoing requests to the outernet because PDNS Recusros won't work for some hosts otherwise
iptables -t mangle -C OUTPUT -o `ip ro sh default | awk {'print $5'}`  -p tcp --dport 53 -j MARK --set-mark "$(jq -r ".route_table_num" /etc/mrvpn.conf)" > /dev/null 2>&1 ||
  iptables -t mangle -A OUTPUT -o `ip ro sh default | awk {'print $5'}`  -p tcp --dport 53 -j MARK --set-mark "$(jq -r ".route_table_num" /etc/mrvpn.conf)"

iptables -t mangle -C OUTPUT -o `ip ro sh default | awk {'print $5'}`  -p udp --dport 53 -j MARK --set-mark "$(jq -r ".route_table_num" /etc/mrvpn.conf)" > /dev/null 2>&1 ||
  iptables -t mangle -A OUTPUT -o `ip ro sh default | awk {'print $5'}`  -p udp --dport 53 -j MARK --set-mark "$(jq -r ".route_table_num" /etc/mrvpn.conf)"
