- name: Deploy
  block:
    - copy:
        content: "{{ vars | to_nice_json }}"
        dest: "/etc/mrvpn.conf"
    - apt:
        name: [ wireguard, docker, docker.io, docker-compose, python3-pip, curl, jq ]
        state: present
        update_cache: yes
    - name: install pexpect
      pip:
        name: pexpect
    - file:
        path: "{{item}}"
        state: directory
        mode: 0755
      with_items:
        - "{{target_dir}}"
        - "{{target_dir}}/conf"
        - "{{target_dir}}/var"
    - include_tasks:
        file: firezone.yml
    - copy:
        src: "files/init_firewall"
        dest: "{{target_dir}}/"
        mode: 0777

    - include_tasks:
        file: containers.yml

    - copy:
        content: "{{wireguard_config}}"
        dest: "/etc/wireguard/mrvpn-wg-outer.conf"

    - name: starting outernet tunnel
      ansible.builtin.systemd:
        name: wg-quick@mrvpn-wg-outer
        state: started
        enabled: yes
        daemon-reload: yes

    - shell:
        cmd: "{{target_dir}}/init_firewall"

    - cron:
        name: "MRVPN init firewall"
        special_time: reboot
        job: "{{target_dir}}/init_firewall"

  become: true