version: "3.3"

services:
  pdns-recursor:
    network_mode: host
    image: pdns-recursor
    build: ./
    pull_policy: build
    #image: pschiffe/pdns-recursor
    #    ports:
    #      - 1053:53
    #      - 1053:53/tcp
    volumes:
      - "./interceptor.lua:/interceptor.lua"

    environment:
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_lua_dns_script=/interceptor.lua
      - PDNS_disable_packetcache=yes
      - PDNS_max_cache_ttl=10
      - PDNS_local_port=1053
